/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vyuzfeiyxztitsupjwob"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dXpmZWl5eHp0aXRzdXBqd29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MDM1OTEsImV4cCI6MjA3NjA3OTU5MX0._INwl_wD6vMTjoprgOWbBm0A4yI7wFePh-e19Abv-V"